version: '3'

services:
  web:
    build:
      context: src
      dockerfile: Dockerfile
    command: python main.py
    environment:
      PSQL_USER: admin
      PSQL_PWD: "${PSQL_PWD}"
    depends_on:
      - db
    ports:
    - 8080:8080

  db:
    container_name: timer_data_db
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: timer_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "${PSQL_PWD}"


volumes:
  pg_data: